export default function Head() {
  return (
    <>
      <title> Panaverse Website</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by shakira Ambreen" />
      <link rel="icon" href="/weblogo.png" />
    </>
  );
}
